import Report from '../models/ReportModel.js';
import Patient from '../models/PatientModel.js';

// @desc    Upload a new Report (PDF)
// @route   POST /api/reports/upload
// @access  Private (Doctor Only)
export const uploadReport = async (req, res) => {
  // req.file is added by Multer middleware
  const { patientId, reportTitle } = req.body;

  try {
    if (!req.file) {
      return res.status(400).json({ message: 'Please upload a PDF file' });
    }

    // 1. Verify Patient Exists
    const patient = await Patient.findById(patientId);
    if (!patient) {
      return res.status(404).json({ message: 'Patient not found' });
    }

    // 2. Save Report Metadata to Database
    // Note: The actual file is already saved in 'uploads/reports' by the route
    const report = await Report.create({
      patientId,
      doctorId: req.user.id,
      reportTitle,
      fileName: req.file.filename, // The timestamped name generated by Multer
      mimeType: req.file.mimetype
    });

    res.status(201).json({
      message: 'Report Uploaded Successfully',
      report
    });

  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get all reports for a specific patient
// @route   GET /api/reports/:patientId
// @access  Private (Doctor & Patient)
export const getReports = async (req, res) => {
  try {
    const reports = await Report.find({ patientId: req.params.patientId })
      .sort({ createdAt: -1 });

    res.json(reports);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};